### ISSUE TITLE
données CSV sur data.gouv

### ISSUE THREAD

**Issue by PatGendre** [laurentg/insee-200m-extract#2]
bonjour Laurent,
j'ai l'occasion d'avoir besoin des données Insee, je me suis souvenu de ton script, mais pour info les données Insee ont été publiées directement en CSV sur data.gouv
https://www.data.gouv.fr/fr/datasets/csv-insee-carroyees-a-200-m-sur-la-population/
ce qui est quand même plus simple !
A bientôt
Patrick

**Comment by laurentg** [comment]
Bonjour Patrick!

Merci pour l'info, je vais mettre un petit commentaire dans la page d'accueil du site pour rediriger sur les données CSV publiées.

**Comment by PatGendre** [comment]
merci Laurent :-)
